"""
NOME/NAME: Raphael Araújo
DATA/DATE: 01/11/2019
[PT]
> Adicione o módulo moeda.py criado nos desafios anteriores, uma função chamada resumo(), que mostre na tela algumas
informações geradas pelas funções que já temos no módulo criado até aqui.
[EN]
> Add the currency.py module created in the previous challenges, a function called summary (), which shows on screen
some information generated by the functions we already have in the module created so far.
"""
import moeda

p = float(input('Digite o preço: R$ '))
moeda.resumo(p)